version: '3.9'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"         # Expose port 5173 for Vite dev server
    volumes:
      - .:/app              # Mount the current directory to the container
      - /app/node_modules   # Avoid overwriting node_modules in the container
    command: npm run dev    # Start the Vite dev server
